### PR TITLE
Fix internet networking

### LINKED ISSUE #156: SERVER_IP hard-coded
Currently the server IP is hard-coded meaning we need to recompile everytime we want to use a different server. An example is localhost vs ungroup.dev. This is annoying.

### PR DESCRIPTION
**Pull request by copacetic**
**Description**

* Send regular no-op UDP packets for NAT traversal
* Add support for using dynamic client IP
* Add support for passing server IP from client cmd line

**Fixes**

Fixes #156, #155, #154

### CODE REVIEW

File: src/client/systems/NetworkingClient.cpp [hunk 1]
```diff
@@ -260,9 +260,34 @@ void NetworkingClient::unreliableSend() {
     }
 }
 
+void NetworkingClient::sendNatPunch() {
```
Comment (copacetic) [inline src/client/systems/NetworkingClient.cpp]: the UDP sending logic here might be possible to dedup but it's kind of annoying since the packets have different arguments here and in the Input command send

File: src/client/systems/NetworkingClient.cpp [hunk 2]
```diff
@@ -12,7 +12,7 @@
 #include "../../common/util/game_settings.hpp"
 #include "../../common/util/network_util.hpp"
 
-const sf::Time CLIENT_TCP_TIMEOUT = sf::milliseconds(100);
+const sf::Time CLIENT_TCP_TIMEOUT = sf::milliseconds(300);
```
Comment (copacetic) [inline src/client/systems/NetworkingClient.cpp]: this timeout might still be too low in a case where we have 500 ms latency, but we probably should just tell the player their connection is too fucked

File: src/client/systems/NetworkingClient.cpp [hunk 3]
```diff
@@ -260,9 +260,34 @@ void NetworkingClient::unreliableSend() {
...
+    } else {
+        std::cout << "Failed to form packet" << std::endl;
+    }
+}
+
 void NetworkingClient::sendUnreliableInput() {
     std::lock_guard<std::mutex> m_unreliableInputs_guard(m_unreliableInputs_lock);
     if (m_unreliableInputs_t.empty()) {
+        srand(time(0));
+        bool send_nat_punch = (rand() % 10 == 0);
```
Comment (copacetic) [inline src/client/systems/NetworkingClient.cpp]: we basically dont want to constantly send nat punches, but how do we decide when to send it? basically we should send it if we haven't sent an input command recently. this was my quick an dirty implementation which didnt involve keeping a timestamp for last sent input command, but I think Ill just switch to the timestamp solution

File: src/client/systems/NetworkingClient.cpp [hunk 4]
```diff
@@ -274,6 +299,7 @@ void NetworkingClient::sendUnreliableInput() {
     UnreliableCommand unreliable_command = {(sf::Uint32)m_clientId_ta, unreliable_input_cmd,
                                             m_tick_ta};
 
+    std::cout << "we sending a UDP packet" << std::endl;
```
Comment (copacetic) [inline src/client/systems/NetworkingClient.cpp]: delete

File: src/client/systems/NetworkingClient.cpp [hunk 5]
```diff
@@ -260,9 +260,34 @@ void NetworkingClient::unreliableSend() {
     }
 }
 
+void NetworkingClient::sendNatPunch() {
+    sf::Packet packet;
+    sf::Uint32 unreliable_input_cmd = UnreliableCommandType::nat_punch;
+    UnreliableCommand unreliable_command = {(sf::Uint32)m_clientId_ta, unreliable_input_cmd,
+                                            m_tick_ta};
+
+    std::cout << "we sending a nat punch" << std::endl;
```
Comment (copacetic) [inline src/client/systems/NetworkingClient.cpp]: delete

File: src/client/systems/NetworkingClient.cpp (hunk 1 above)
Comment (copacetic) [reply src/client/systems/NetworkingClient.cpp]: maybe the sending function will just take a packet that you want sent

File: src/common/util/game_settings.hpp [hunk 6]
```diff
@@ -71,8 +71,8 @@ const std::chrono::milliseconds SERVER_BROADCAST_GAME_STATE_SLEEP(16);
 const std::chrono::milliseconds CLIENT_UNRELIABLE_RECV_SLEEP(SERVER_BROADCAST_GAME_STATE_SLEEP / 2);
 
 /* Networking */
-static const char* CLIENT_IP = "127.0.0.1";
+static const char* CLIENT_IP = "73.15.213.77";
```
Comment (copacetic) [inline src/common/util/game_settings.hpp]: I dont want to commit this, so Im going to implement dynamically learning the client IP and using it before merging

File: src/client/systems/NetworkingClient.hpp [hunk 7]
```diff
@@ -56,6 +58,10 @@ class NetworkingClient {
     // Sockets
     void createTcpSocket(unsigned short port);
     void createUdpSocket();
+    void sendUnreliable(sf::Packet packet);
+
+    time_t m_last_sent_nat_punch = time(0) - NAT_PUNCH_INTERVAL;
+    std::string m_server_ip;
```
Comment (SourenP) [inline src/client/systems/NetworkingClient.hpp]: The style for member variables is camelcase - `m_serverIp` or `m_serverIP`

File: src/client/systems/NetworkingClient.hpp [hunk 8]
```diff
@@ -56,6 +58,10 @@ class NetworkingClient {
     // Sockets
     void createTcpSocket(unsigned short port);
     void createUdpSocket();
+    void sendUnreliable(sf::Packet packet);
+
+    time_t m_last_sent_nat_punch = time(0) - NAT_PUNCH_INTERVAL;
```
Comment (SourenP) [inline src/client/systems/NetworkingClient.hpp]: `m_lastSentNatPunch`

File: src/common/util/game_settings.hpp [hunk 9]
```diff
@@ -38,6 +38,7 @@ const bool SHOW_PLAYER_IDS = true;
 /* Game Logic */
 const bool USE_INTERPOLATION_REPLAY = false;
 
+const int NAT_PUNCH_INTERVAL = 30;
```
Comment (SourenP) [inline src/common/util/game_settings.hpp]: Do we really need to send this every 30ms? 
How do we know what to make this interval, what does it depend on? 

Would it work if we just did it once at the start of the connection and then never again?

Comment (SourenP) [reply src/common/util/game_settings.hpp]: Oh just read your commit comment. 30sec sounds good

Btw I would use the sfml [clock](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Clock.php) module instead of `<time.h>`. It has this nice feature where you can just get the elapsed time since the last time you called `clock.reset()` and its syntax makes the granularity of time very explicit e.g. `clock.getElapsedTime().asSeconds()`

Comment (copacetic) [reply src/common/util/game_settings.hpp]: that's cool, I think I'll hold off on changing the code since it's fine and it's actually a different way of thinking about the problem to use a clock and elapsed time vs sampling the current time and keeping a timestamp. Rather spend my brainwaves on more core problems for Prototype 1
